name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Module
        run: deno task test

      - name: Publish package
        run: npx jsr publish
